# 14章　非同期プログラミング
非同期の処理が必要とされるものは主に次の4種類である。  

- ユーザーからの入力
- ネットワーク経由のリクエスト(たとえばAjax呼び出し)
- ファイルシステム関連の操作(ファイルの読み書きなど)
- 意図的に遅延された操作(たとえばアラーム)

JavaScriptはシングルスレッドである。  
JavaScriptでは非同期プログラミングの改良が進められた。改良によるこれまでの仕様は、主に3つに分けられる。  
ジェネレータもプロミスもコールバックを使って非同期の処理を実現している。  

- コールバック
- プロミス
- ジェネレータ
- (async/await)ES2017以降


## 14.1　非同期処理のアナロジー
各非同期処理は以下のようなアナロジーで表現できる。 
- コールバッック
  - 携帯電話の番号を伝えておくと席が空いたときに知らせてくれるシステム
  - 連絡を受け取る自前の端末が必要
- プロミス
  - ポケベルを渡してくれて席が空いたときに知らせてくれる
  - 連絡を受け取る端末を相手が提供してくれる


## 14.2　コールバック
JavaScriptのコールバックは「将来のある時点で呼び出される関数」のことである。 
コールバックには無名関数やアロー関数がよく使われる。 

JavaScriptはシングルスレッドであり、上から順番に読まれていく。  
非同期処理は「待ち(ブロック)」が生じないところがポイントである。  
```js
// 非同期処理のわかりやすい例
// もしsetTimeoutで10秒、待っていたら次の処理が遅れる
console.log("setTimeoutの前: " + new Date());
function f() {
  console.log("これは関数fの中: " + new Date());
}
setTimeout(f, 10*1000); /* 10秒後にfを実行。コールバック */
console.log("setTimeoutの後");
console.log("これもsetTimeoutの後");

/* 実行結果
setTimeoutの前: Thu Oct 27 2016 18:02:54 GMT+0900 (JST)
setTimeoutの後
これもsetTimeoutの後
これは関数fの中: Thu Oct 27 2016 18:03:04 GMT+0900 (JST)
*/
```
通常使われる無名関数の例  
コールバック関数の第1引数に無名関数、第2引数には時間を指定している  
```js
console.log("setTimeoutの前：" + new Date());
setTimeout(
  function() {
    console.log("setTimeoutに指定された無名関数の中：" + new Date()); // setTimeoutの第1引数
  },
  10*1000 // setTimeoutの第2引数
);
console.log("setTimeoutの後");
console.log("これもsetTimeoutの後");
```
アロー関数で書くと次のようになる
```js
console.log("setTimeoutの前：" + new Date());
setTimeout( () => console.log("アロー関数の中：" + new Date()), 10*1000);
console.log("setTimeoutの後");
console.log("これもsetTimeoutの後");
```

### 14.2.1　setIntervalとclearInterval
- setInterval
  - 指定の間隔でコールバックを繰り返し実行する
  - setIntervalはタイマーを停止するためのIDを返す
  - clearIntervalにIDを渡して停止する
5秒ごとに10回、現在時刻を表示する 
```js
const start = new Date();
let i=0;
const intervalId = setInterval(function() {
  let now = new Date() // 現在時刻を得る
  if(++i>10)
    return clearInterval(intervalId);
  console.log(`${i}: ${now}`);
}, 5*1000);
```

now.getMinutes() !== start.getMinutes() || 
### 14.2.2　スコープと非同期の実行
スコープによっては、コールバックの実行と連動させたい値が噛み合わない場合がある。 
非同期処理と同期処理で値が変わってしまう。
```js
// iはスコープ内の
function countdown() {
  let i; /* iをループの外で定義していることに注意 */
  console.log("カウントダウン：");
  for(i=5; i>=0; i--) { // これも同期処理
    setTimeout(function() { // こちらも同期処理
      console.log(i===0 ? "GO!" : i); // setTimeoutに渡された関数だけが非同期で処理されている。
                                      // だからiの値をforループ内でブロックしておかなければ、毎回のループでiが代入されるのではなく、既に終わった値だけが代入されて出力される
    }, (5-i)*1000); // これは同期処理
  }
}
countdown();
```
ブロックスコープletをfor文の中で宣言すれば、iはfor文のiに限定されてループごとに代入される 
```js
function countdown() {
  console.log("カウントダウン：");
  for(let i=5; i>=0; i--) { /* iはブロックスコープ */
    setTimeout(function() {
      console.log(i===0 ? "GO!" : i);
    }, (5-i)*1000);
  }
};
countdown();
```
IIFEでクロージャを形成することでiを閉じ込めることもできる。letを使った方がわかりやすい。 
```js
function countdown(){
let i;
for(i=5; i>=0; i--){
  (function(i) {
    setTimeout(function() {
      console.log(i===0 ? "go!" : i );
    }, (5-i)*1000)})(i);
}
}
countdown();
```

### 14.2.3　エラーファースト・コールバック
エラーファースト・コールバックは、Nodeの開発における事実上の標準である。  
これは**コールバックの第1引数をエラーオブジェクトを受け取るために使う**という標準である。 
コールバックを使う際はこの慣習に従う。 
```js
const fs = require('fs');

const fname = 'xxx'; // 存在しないファイル名を指定
fs.readFile(fname, function(err, date) { // エラーファーストコールバック。コールバックの第1引数で「errオブジェクト」を受け取る。
  if(err)
    return console.error(`ファイルの読み込み時のエラー ${fname}: ${err.message}`);
  console.log(`ファイル「${fname}」の内容を表示します： \n${data}`);
});
```

### 14.2.4　コールバック地獄
コールバック時刻は、複数のコールバックを待つ必要があり、深い入れ子になっている状態を指す。 
特にエラー処理が大変になる。　
```js
/* Node.jsで実行 */
const fs = require('fs');

fs.readFile('a.txt', function(err, dataA) {
  if(err) console.error(err);
  fs.readFile('b.txt', function(err, dataB) {
    if(err) console.error(err);
    fs.readFile('c.txt', function(err, dataC) {
      if(err) console.error(err);
      fs.writeFile('d.txt', dataA+dataB+dataC, function(err) {
        if(err) console.error(err);
      });
    });
  });
});
```
...?  
実際は動いていない。  
try...catchブロックは同じ関数でしか機能しない。この場合、``function(err, date){}``内で例外がスローされている。  
```js
/* Node.jsで実行 */
const fs = require('fs');
function readSketchyFile() { /* sketchy: 怪しげな, 疑わしい */
  try {
    fs.readFile('does_not_exist.txt', function(err, data) {
      if(err) throw err;
      else console.log('無事読み込めました')
    });
  } catch(err) {
    console.log('警告：マイナーな問題が発生。実行を継続します');
  }
}
readSketchyFile();

/* 実行結果
      if(err) throw err;
              ^
Error: ENOENT: no such file or directory, open 'does_not_exist.txt'
*/
```

## 14.3　プロミス（Promise）
プロミスを呼び出すと、オブジェクトPromiseのインスンタスが返される
インスタンスには非同期な処理がラップされている
プロミスは成功あるいは失敗のいずれか。成功あるいは失敗したら確定される。そうでない場合はペンディング(留保)中。

funcP(非同期処理の関数)を呼び出したら、インスタンス(Promiseオブジェクトの)が返される。
インスンタスからpromiseのメソッドを呼び出す形で、成功と失敗に場合分けして、行うべき処理を別々の関数に記述する

例えば非同期的な処理が成功したならonFullfilled、失敗したならonRejceted

### 14.3.1　プロミスの生成

プロミスの生成  
``new Promise(<非同期処理を記述した関数>);``  
成功と失敗のそれぞれの場合に実行される2つの関数を指定  
```js
new Promise(
  function(onFulfilled, onRejected) {
    ... // 非同期の処理を記述
  }
)
```
countdownの関数をプロミスベースにする。  
```js
function countdown(seconds) {
  return new Promise(
    function(onFulfilled, onRejected) {
      let seconds = new Date().getSeconds();
      for(let i=seconds; i>=0; i--) {
        setTimeout(function() {
          if(i>0) console.log(i + '...')
          else onFulfilled(console.log("GO!"));
        }, (seconds-i)*1000);
      }
    }
  )
}
countdown(5);
```
### 14.3.2　プロミスの利用
```js
function countdown(seconds) {
  return new Promise(function(onFulfilled, onRejected) {
    const timeoutIds = [];
    for(let i=seconds; i>=0; i--) {
      timeoutIds.push(setTimeout(
	function() {
      if(i===13) {
	    timeoutIds.forEach(clearTimeout); /* すべてクリア。forEachは9章参照　*/
	    onRejected(new Error(`${i}という数は不吉過ぎます`));
	  }
          else if(i>0) {
	    console.log(i + '...');
	  }
          else {
	    console.log("GO!");
	    onFulfilled();
	  }
	}, /* 無名関数の終わり */
	(seconds-i)*1000))
    }
  });
}
countdown(15).then(
  function() {
    console.log("カウントダウン成功");
  },
  function(err) {
    console.log("カウントダウンでエラーが起こった：" + err.message);
  }
);
```

### 14.3.3　プロミスの基本パターン
プロミスの基本パターンは以下のようになる。 

```js
function asyncFunc(paramsAsyncFunc) {
  return new Promise(
    function(onfulfilled, onRejected) {
      <非同期処理の記述>
      ...
      onFulfilled(paramsOnFulfilled); // 成功の場合。引数を経由して値を呼び出し側に渡せる
      ...
      onRejected(paramsOnRejected); // 失敗の場合。なくても可。
    }
  );
}

asyncFunc(paramsAsyncFunc).then(
  function(paramsOnfulfilled) {
    // 成功時の処理。paramsOnFulfilled経由で非同期処理から値を受け取れる
  }
  function(paramsOnRejected) {
    // エラー発生時の処理。paramsOnRejected経由で非同期処理から値を受け取れる
  }
)
```
catchハンドラを使って、エラーなどが発生したときの処理をthenとは独立させて書く  

### 14.3.4 プロミスのチェイニング
チェイニングして、次のプロミス、その次のプロミスの実行を連鎖できる。 


```js
function countdown(seconds) {
  return new Promise(function(onFulfilled, onRejected) {
    const timeoutIds = [];
    for(let i=seconds; i>=0; i--) {
      timeoutIds.push(setTimeout(function() {
        if(i===13) {
          timeoutIds.forEach(clearTimeout); /* すべてクリア */
	  return onRejected(new Error(`${i}という数は不吉過ぎます`));
	}
        if(i>0) console.log(i + '...');
        else onFulfilled(console.log("GO!"));
      }, (seconds-i)*1000))
    }
  });
}

function launch() {
  return new Promise(function(onFulfilled, onRejected) {
    console.log("発射!");
    setTimeout(function() {
      onFulfilled("周回軌道に乗った！");
    }, 5*1000); /* 超速のロケット */
  });
}

function landing() {
  return new Promise(function(onFulfilled, onRejected) {
    console.log("着陸できるか？");
    setTimeout(function() {
      onFulfilled("月面に着陸した！");
    }, 5*1000);
  });
}

countdown(12)
  .then(launch)
  .then(function(msg) { /* 関数launch内のonFulfilledの引数がmsgに渡る */
    console.log(msg); // 周回軌道に乗った！  （成功した場合）
  })
  .catch(function(err) {
    console.error("管制塔、管制塔。トラブル発生... " + err);
  })
  .then(landing)
  .then(function(msg) {
    console.log(msg);
  })
  .catch(function(err) {
    console.error("管制塔、管制塔。トラブル発生... " + err);
  })
```
3つのファイル(a.txt、b.txt、c.txt)を非同期に読み込んで、準備が完了したらd.txtに内容を書き込むプログラム  
```js
'use strict';
const fs = require('fs');

function readfile(fileName) {
  return new Promise(
    (onFulfilled, onRejected) => {
      fs.readFile(fileName, "utf-8", (err, data)=>{
        // console.log(data);
        if(err) {
          console.error("readFile error:" + fileName + err);
          onRejected(err);
        }
        onFulfilled(data);
      });
    });
}

function writeFile(fileName, data) {
  return new Promise(
    (onFulfilled, onRejected) => {
      fs.writeFile(fileName, data, err=> {
        if (err) {
          console.error("writeFile error:" + fileName + err);
          onRejected(err);
        }
        onFulfilled("OK");
      });
    });
}

let allData = "";
readFile("a.txt")
.then(function(fileData) {
  allData += fileData;
  return readFile("b.txt"); // プロミスを返してチェイニング可能にする
})
.then(function(fileData) {
  allData += fileData;
  return readFile("c.txt");
})
.then(function(fileData) {
  allData += fileData;
  return writeFile("d.txt", allData);
})
.then(function(mes) {
  console.log("ファイルの合体に成功しました。");
})
.catch(err => {
  console.error("エラーが起こりました：" + err);
});
```
### 14.3.5　Promise.allとPromise.race
Promise.allを使えば、並行に行う処理を記述できる。  
引数に配列を指定すると、結果も配列で返される。  
並行に実行される処理のうち、どれかひとつが失敗したら全体が失敗となる。  
```js
// 3つのファイルの読み込みを同時に行う
Promise.all([readFile("a.txt"), readFile("b.txt"), readFile("c.txt")])
.then(function(results) {
  // 実行結果(results)も配列になる
  const allData = results[0] + results[1] + results[3];
  return writeFile("d.txt", allData); // プロミスを返してチェイニング可能にする
})
.then(function(mes) {
  console.log("ファイルの合体に成功しました");
})
.catch(err => {
  console.error("エラーが起こりました：" + err);
});
```
Promise.raceを使えば、複数の処理のうちで最も早く確定した結果が採用される。  
```js
const fs = require('fs');

function writeFile(fileName, data) {
  return new Promise((onFulfilled, onRejected) => {
    fs.writeFile(fileName, data, err=>{
      err ? onRejected(err) : onFulfilled('OK');
    }); });
}

function readFile(fileName) {
  return new Promise((onFulfilled, onRejected) => {
    const period = Math.random()*1000;
    console.log(`${fileName}: ${period}`);
    setTimeout(() => {
      fs.readFile(fileName, "utf-8", (err, data) => {
	err ? onRejected(err) : onFulfilled([fileName, data]);
      }); /* fs.readFile */
    }, period); /* setTimeout */
  }); /* Promise */
}

/* 3つのファイルの読み込みを同時に行い、最初に返ってきたものを採用 */
let selected;
Promise.race([readFile("a.txt"), readFile("b.txt"), readFile("c.txt")])
.then(function(results) {
  selected = results[0];
  return writeFile("d.txt", results[1]);
})
.then(function(mes) {
  console.log(`ファイル${selected}の内容が書き込まれました。\n----`);
})
.catch(err => {
  console.error("エラーが起こりました:" + err);
});
```
### 14.3.6　未確定の（unsettled）プロミスを防止する
未確定のプロミスには、タイムアウトを指定する。  
タイムアウトを指定することで、未確定のプロミスを発見できる。  
```js
function countdown(seconds) {
  return new Promise(function(onFulfilled, onRejected) {
    const timeoutIds = [];
    for(let i=seconds; i>=0; i--) {
      timeoutIds.push(setTimeout(function() {
        if(i===13) {
          timeoutIds.forEach(clearTimeout); /* すべてクリア */
	  return onRejected(new Error(`${i}という数は不吉過ぎます`));
	}
        if(i>0) console.log(i + '...');
        else onFulfilled(console.log("GO!"));
      }, (seconds-i)*1000))
    }
  });
}

function launch() {
  return new Promise(function(onFulfilled, onRejected) {
    if(Math.random() < 0.5) /* 打ち上げ失敗 */
//      return onRejected(new Error("打ち上げ失敗！"));
      return;
    console.log("発射!");
    setTimeout(function() {
      onFulfilled("周回軌道に乗った！");
    }, 2*1000); /* 超速のロケット */
  });
}

function addTimeout(fn, /* タイムアウトをアタッチする関数 */
		    period /* タイムアウトの時間 */
		   ) {
  if(period === undefined) period = 1000; /* デフォルトの設定 */
  return function(...args) {
    return new Promise(function(onFulfilled, onRejected) {
      const timeoutId = setTimeout(onRejected, period,
			     new Error("プロミス タイムアウト"));
      fn(...args)
        .then(function(...args) {
          clearTimeout(timeoutId);
          onFulfilled(...args);
        })
        .catch(function(...args) {
          clearTimeout(timeoutId);
          onRejected(...args);
        });
    });
  }
}

countdown(3)
  .then(addTimeout(launch, 4*1000)) /* タイムアウトを4秒に設定 */
  .then(function(msg) {
    console.log(msg);
  })
  .catch(function(err) {
    console.error("管制塔、管制塔。トラブル発生... " + err.message);
  });
```
現在はプロミスの進行状況をレポートする方法がない。ライブラリによっては提供されている。 

## 14.4　ジェネレータ(?)
ジェネレータとプロミスを組み合わせると、非同期処理を同期処理みたいにわかりやすく書ける。

### 14.4.1　ジェネレータランナー
まずはジェネレータランナーを作る。  
```js
// ジェネレータランナー
function grun(g) {
  const it = g();

  (function iterate(val) {
    const x = it.next(val);
    if(!x.done) {
      if(x.value instanceof Promise) {
        x.value.then(iterate).catch(err => it.throw(err));
      } else {
        setTimeout(iterate, 0, x.value);
      }
    }
  })();
}

function readFile(fileName) {
  return new Promise(
    (onFulfilled, onRejected) => {
      fs.readFile(fileName, "utf-8",
                  (err, data) => err ? onRejected(err) : onFulfilled(data));
    })
}

function writeFile(fileName, data) {
  return new Promise(
    (onFulfilled, onRejected) => {
      fs.writeFile(fileName, data, err => err ? onRejected(err) : onFullfilled("OK"));
    });
}

function* fileReadAndWrite() {
  const dataA = yield readFile('a.txt');
  const dataB = yield readFile('b.txt');
  const dataC = yield readFile('c.txt');
  yield writeFile('d.txt', dataA+dataB+dataC);
}

grun(fileReadAndWrite);
```

### 14.4.2　ジェネレータランナーの例外処理
例外処理はコールバックの中でスローしてもコールバックの外では使えない。  
ジェネレータランナーを使えば、try...catchを使った例外処理が可能になる。  
同期的な書き方は「読みやすい」という利点がある。  
```js
function* fileReadAndWrite() {
  try {
    const data = yield Promise.all([readFile('a.txt'),readFile('b.txt'),readFile('c.txt')]);
    yield writeFile('d.txt', data[0]+data[1]+data[2]);
  } catch (err) {
    console.error("エラーが起こりました：" + err);
  }
}
grun(fileReadAndWrite);
```

## 14.5　まとめ
- JavaScript における非同期の実行はコールバックを使って行われる。
- プロミスはコールバックを置き換えるわけではない。then や catch でコールバックを利用する。
- プロミスはあるコールバックが複数回呼ばれてしまうという問題を回避してくれる。
- プロミスが確定(settled)することは保証はできないが、タイムアウトでラップすることでこの問題を回避できる。
- プロミスはチェインにして連続した処理を行うことができる。
- プロミスはジェネレータランナーと組み合わせることができ、同期処理的な書き方で非同期の実行の効果を得ることができる。
- 同期処理的な書き方でジェネレータ関数を書くときはどの部分のコードを並列に実行してもよいか慎重に検討し、そうした部分を Promise.all で実行する。
- ジェネレータランナーは自分で書かずにco(https://github.com/tj/co)や Koa(http://koajs.com/)を利用すべきである。
- Node スタイルのコールバックをプロミスに変換するのに、独自のコードを書くべきではない。Q(https://github.com/kriskowal/q)を使うべきである。
- ジェネレータランナーを使うことで、例外処理を同期処理的な書き方で行うことができる。